### ISSUE TITLE
Newer version of collections not working

### ISSUE THREAD

**Issue by juhanikarlsson** [jeffvella/UnityEcsEvents#1]
Hi,
Looks promising! However it gives errors with newer versions of Unity collections - just heads up : ))

Cheers,
- J

**Comment by jeffvella** [comment]
Thanks! I have an updated version that should be out soon. What has been holding it up was a bug in Unity causing asmrefs to not be set up properly in projects. The new version will extend Entities rather than hacking it to get access to private/internal methods,  which should be cleaner and less likely to break.

**Comment by jeffvella** [comment]
Should be resolved now for "com.unity.collections": "0.9.0-preview.6",

**Comment by juhanikarlsson** [comment]
Hi! Thanks and thanks again for fantastic work! : ))

Cheers,
-J
